# ======================================================================
#  content.py — ALL practice content, baked in. NO API, ever.
# ======================================================================
# This is what makes SpeakUp work with zero keys, zero rate limits, and
# zero per-user cost. Everything a learner drills or says is in here.
#
# HOW TO ADD MORE (you'll want to, over time):
#   - SENTENCE_BANK: add {"en": "...", "ar": "..."} lines under a level.
#     The app randomises order, so more sentences = more variety per session.
#   - CONVERSATIONS / SPRINT_CONVS: add or edit branching dialogue nodes.
#     Each node is one thing the character says + the replies the learner
#     can choose from. Each reply points to the next node id ("goto").
#
# Translations here are Arabic (the default). To support another language
# you can add more keys (e.g. "ku" for Kurdish) — the app falls back to
# English if a translation is missing, so partial is fine.
# ======================================================================


# ----------------------------------------------------------------------
# 1) SENTENCE BANK — for the timed drilling sessions
# ----------------------------------------------------------------------
# Grouped by level. Each entry: the English to say, plus its Arabic meaning.
# Keep them things a real person actually says out loud.
SENTENCE_BANK = {
    "Beginner": [
        {"en": "Hello, how are you today?", "ar": "مرحباً، كيف حالك اليوم؟"},
        {"en": "Nice to meet you.", "ar": "سعيد بلقائك."},
        {"en": "My name is Ali. What's yours?", "ar": "اسمي علي. ما اسمك؟"},
        {"en": "Where are you from?", "ar": "من أين أنت؟"},
        {"en": "I'm from Iraq.", "ar": "أنا من العراق."},
        {"en": "Can you help me, please?", "ar": "هل يمكنك مساعدتي، من فضلك؟"},
        {"en": "How much does this cost?", "ar": "كم يكلف هذا؟"},
        {"en": "I would like a coffee, please.", "ar": "أريد قهوة، من فضلك."},
        {"en": "Where is the bathroom?", "ar": "أين الحمام؟"},
        {"en": "What time is it?", "ar": "كم الساعة؟"},
        {"en": "I don't understand. Can you repeat that?", "ar": "لا أفهم. هل يمكنك تكرار ذلك؟"},
        {"en": "Thank you very much.", "ar": "شكراً جزيلاً."},
        {"en": "You're welcome.", "ar": "على الرحب والسعة."},
        {"en": "Excuse me, where is the station?", "ar": "المعذرة، أين المحطة؟"},
        {"en": "I'm sorry, I'm late.", "ar": "أنا آسف، لقد تأخرت."},
        {"en": "See you tomorrow.", "ar": "أراك غداً."},
        {"en": "Have a nice day.", "ar": "أتمنى لك يوماً سعيداً."},
        {"en": "What do you do for work?", "ar": "ما هو عملك؟"},
        {"en": "I am a student.", "ar": "أنا طالب."},
        {"en": "Can I have the menu, please?", "ar": "هل يمكنني الحصول على القائمة، من فضلك؟"},
        {"en": "The weather is nice today.", "ar": "الطقس جميل اليوم."},
        {"en": "I like this place.", "ar": "يعجبني هذا المكان."},
        {"en": "How do I get to the airport?", "ar": "كيف أصل إلى المطار؟"},
        {"en": "Could you speak more slowly?", "ar": "هل يمكنك التحدث ببطء أكثر؟"},
        {"en": "I need some water.", "ar": "أحتاج بعض الماء."},
        {"en": "This is delicious.", "ar": "هذا لذيذ."},
        {"en": "Can I pay by card?", "ar": "هل يمكنني الدفع بالبطاقة؟"},
        {"en": "I'm looking for a hotel.", "ar": "أبحث عن فندق."},
        {"en": "It was nice talking to you.", "ar": "كان من الجميل التحدث معك."},
        {"en": "Good morning, everyone.", "ar": "صباح الخير للجميع."},
        {"en": "What's your phone number?", "ar": "ما هو رقم هاتفك؟"},
        {"en": "I live near the city center.", "ar": "أسكن قرب وسط المدينة."},
        {"en": "Do you have any brothers or sisters?", "ar": "هل لديك إخوة أو أخوات؟"},
        {"en": "My family is very important to me.", "ar": "عائلتي مهمة جداً بالنسبة لي."},
        {"en": "I wake up early every morning.", "ar": "أستيقظ مبكراً كل صباح."},
        {"en": "What did you have for breakfast?", "ar": "ماذا تناولت في الفطور؟"},
        {"en": "I usually go to bed at eleven.", "ar": "أذهب للنوم عادةً في الساعة الحادية عشرة."},
        {"en": "Do you drink tea or coffee?", "ar": "هل تشرب الشاي أم القهوة؟"},
        {"en": "I'm hungry. Let's get something to eat.", "ar": "أنا جائع. لنحضر شيئاً لنأكله."},
        {"en": "This food is too spicy for me.", "ar": "هذا الطعام حار جداً بالنسبة لي."},
        {"en": "Can I get the check, please?", "ar": "هل يمكنني الحصول على الفاتورة من فضلك؟"},
        {"en": "Is it going to rain today?", "ar": "هل ستمطر اليوم؟"},
        {"en": "It's very hot outside.", "ar": "الجو حار جداً في الخارج."},
        {"en": "I need to buy an umbrella.", "ar": "أحتاج لشراء مظلة."},
        {"en": "What's the weather like tomorrow?", "ar": "كيف سيكون الطقس غداً؟"},
        {"en": "I love sunny days.", "ar": "أحب الأيام المشمسة."},
        {"en": "How much does this shirt cost?", "ar": "كم يكلف هذا القميص؟"},
        {"en": "Do you have this in a different color?", "ar": "هل لديكم هذا بلون مختلف؟"},
        {"en": "I'm just looking, thank you.", "ar": "أنا فقط أنظر، شكراً."},
        {"en": "Where can I find the exit?", "ar": "أين يمكنني إيجاد المخرج؟"},
        {"en": "Is there a supermarket nearby?", "ar": "هل يوجد سوبرماركت قريب من هنا؟"},
        {"en": "I need to buy some vegetables.", "ar": "أحتاج لشراء بعض الخضروات."},
        {"en": "How many do you need?", "ar": "كم تحتاج منها؟"},
        {"en": "That's too expensive for me.", "ar": "هذا غالٍ جداً بالنسبة لي."},
        {"en": "Do you accept cash?", "ar": "هل تقبلون الدفع نقداً؟"},
        {"en": "I feel a little tired today.", "ar": "أشعر بتعب قليل اليوم."},
        {"en": "I'm very happy to see you.", "ar": "أنا سعيد جداً برؤيتك."},
        {"en": "I'm a bit nervous about the exam.", "ar": "أنا متوتر قليلاً بشأن الامتحان."},
        {"en": "Don't worry, everything will be fine.", "ar": "لا تقلق، كل شيء سيكون بخير."},
        {"en": "I'm proud of you.", "ar": "أنا فخور بك."},
        {"en": "This makes me really happy.", "ar": "هذا يجعلني سعيداً حقاً."},
        {"en": "What time does the bus arrive?", "ar": "متى تصل الحافلة؟"},
        {"en": "How far is the airport from here?", "ar": "كم تبعد المطار من هنا؟"},
        {"en": "I need a taxi to the hotel.", "ar": "أحتاج سيارة أجرة إلى الفندق."},
        {"en": "Is this seat taken?", "ar": "هل هذا المقعد محجوز؟"},
        {"en": "Turn right at the next corner.", "ar": "انعطف يميناً عند الزاوية القادمة."},
        {"en": "I think we're going the wrong way.", "ar": "أظن أننا نسير في الاتجاه الخاطئ."},
        {"en": "How long is the flight?", "ar": "كم تستغرق الرحلة؟"},
        {"en": "Where should I check in?", "ar": "أين يجب أن أسجّل وصولي؟"},
        {"en": "I have a headache.", "ar": "لدي صداع."},
        {"en": "I need to see a doctor.", "ar": "أحتاج لرؤية طبيب."},
        {"en": "Where is the nearest pharmacy?", "ar": "أين أقرب صيدلية؟"},
        {"en": "I feel much better now.", "ar": "أشعر بتحسن كبير الآن."},
        {"en": "Take care of yourself.", "ar": "اعتنِ بنفسك."},
        {"en": "My phone battery is almost dead.", "ar": "بطارية هاتفي شبه فارغة."},
        {"en": "Can I borrow your charger?", "ar": "هل يمكنني استعارة الشاحن الخاص بك؟"},
        {"en": "What's the Wi-Fi password?", "ar": "ما هي كلمة مرور الواي فاي؟"},
        {"en": "My computer isn't working.", "ar": "حاسوبي لا يعمل."},
        {"en": "Can you send me the file?", "ar": "هل يمكنك إرسال الملف لي؟"},
        {"en": "What do you like to do in your free time?", "ar": "ماذا تحب أن تفعل في وقت فراغك؟"},
        {"en": "I enjoy playing football.", "ar": "أستمتع بلعب كرة القدم."},
        {"en": "Do you like watching movies?", "ar": "هل تحب مشاهدة الأفلام؟"},
        {"en": "I like listening to music.", "ar": "أحب الاستماع إلى الموسيقى."},
        {"en": "Let's go for a walk.", "ar": "لنذهب في نزهة."},
        {"en": "Hello, may I speak to Ahmed, please?", "ar": "مرحباً، هل يمكنني التحدث مع أحمد من فضلك؟"},
        {"en": "Can I leave a message?", "ar": "هل يمكنني ترك رسالة؟"},
        {"en": "I'll call you back later.", "ar": "سأتصل بك لاحقاً."},
        {"en": "Sorry, I have the wrong number.", "ar": "آسف، لدي رقم خاطئ."},
        {"en": "Can you hear me clearly?", "ar": "هل تسمعني بوضوح؟"},
        {"en": "What grade are you in?", "ar": "في أي صف أنت؟"},
        {"en": "I study at the university.", "ar": "أدرس في الجامعة."},
        {"en": "My favorite subject is science.", "ar": "مادتي المفضلة هي العلوم."},
        {"en": "Homework is due tomorrow.", "ar": "الواجب موعد تسليمه غداً."},
        {"en": "Congratulations on your graduation!", "ar": "تهانينا على تخرجك!"},
        {"en": "I start work at nine o'clock.", "ar": "أبدأ العمل في الساعة التاسعة."},
        {"en": "My boss is very kind.", "ar": "مديري لطيف جداً."},
        {"en": "I have a meeting this afternoon.", "ar": "لدي اجتماع بعد الظهر."},
        {"en": "I need a day off next week.", "ar": "أحتاج يوم إجازة الأسبوع القادم."},
        {"en": "Good luck with your interview.", "ar": "بالتوفيق في مقابلتك."},
        {"en": "Happy birthday!", "ar": "عيد ميلاد سعيد!"},
        {"en": "Congratulations on the new baby.", "ar": "تهانينا بالمولود الجديد."},
        {"en": "I'm getting married next month.", "ar": "سأتزوج الشهر القادم."},
        {"en": "We're celebrating our anniversary.", "ar": "نحتفل بذكرى زواجنا."},
        {"en": "I'm sorry for your loss.", "ar": "أنا آسف لخسارتك."},
        {"en": "Can you pass me the salt, please?", "ar": "هل يمكنك تمرير الملح لي من فضلك؟"},
        {"en": "This tastes really good.", "ar": "طعم هذا لذيذ جداً."},
        {"en": "I'm allergic to nuts.", "ar": "لدي حساسية من المكسرات."},
        {"en": "Could I have some more water?", "ar": "هل يمكنني الحصول على المزيد من الماء؟"},
        {"en": "I don't eat meat.", "ar": "أنا لا آكل اللحم."},
        {"en": "Where do you want to sit?", "ar": "أين تريد أن تجلس؟"},
        {"en": "This place has a nice view.", "ar": "هذا المكان له إطلالة جميلة."},
        {"en": "Let's meet at the entrance.", "ar": "لنلتقِ عند المدخل."},
        {"en": "I'll be there in ten minutes.", "ar": "سأصل خلال عشر دقائق."},
        {"en": "Sorry I'm late, there was traffic.", "ar": "آسف على التأخير، كان هناك ازدحام."},
        {"en": "Can we reschedule for another day?", "ar": "هل يمكننا تحديد موعد آخر ليوم مختلف؟"},
        {"en": "I have an appointment at three.", "ar": "لدي موعد الساعة الثالثة."},
        {"en": "What day works best for you?", "ar": "أي يوم يناسبك أكثر؟"},
        {"en": "I'm free this weekend.", "ar": "أنا متفرغ في نهاية هذا الأسبوع."},
        {"en": "Let's plan something fun.", "ar": "لنخطط لشيء ممتع."},
        {"en": "I forgot my umbrella at home.", "ar": "نسيت مظلتي في المنزل."},
        {"en": "Can I open the window?", "ar": "هل يمكنني فتح النافذة؟"},
        {"en": "It's a bit cold in here.", "ar": "الجو بارد قليلاً هنا."},
    ],
    "Intermediate": [
        {"en": "Could you tell me a bit about yourself?", "ar": "هل يمكنك أن تخبرني قليلاً عن نفسك؟"},
        {"en": "I've been learning English for two years.", "ar": "أتعلم الإنجليزية منذ عامين."},
        {"en": "I was wondering if you could help me.", "ar": "كنت أتساءل إن كان بإمكانك مساعدتي."},
        {"en": "That sounds like a great idea.", "ar": "تبدو فكرة رائعة."},
        {"en": "I'm not sure I agree with that.", "ar": "لست متأكداً من أنني أوافق على ذلك."},
        {"en": "Let me think about it for a moment.", "ar": "دعني أفكر في الأمر للحظة."},
        {"en": "What would you recommend?", "ar": "بماذا تنصح؟"},
        {"en": "I'd rather not talk about that right now.", "ar": "أفضّل ألا أتحدث عن ذلك الآن."},
        {"en": "Do you mind if I ask you something?", "ar": "هل تمانع أن أسألك شيئاً؟"},
        {"en": "It depends on the situation.", "ar": "هذا يعتمد على الموقف."},
        {"en": "I completely understand what you mean.", "ar": "أفهم تماماً ما تقصده."},
        {"en": "Could you explain that in more detail?", "ar": "هل يمكنك شرح ذلك بمزيد من التفصيل؟"},
        {"en": "I'm afraid there's been a mistake.", "ar": "أخشى أنه حدث خطأ."},
        {"en": "Let's schedule a meeting for next week.", "ar": "لنحدد موعداً لاجتماع الأسبوع القادم."},
        {"en": "I really appreciate your help.", "ar": "أقدّر مساعدتك حقاً."},
        {"en": "That's exactly what I was thinking.", "ar": "هذا بالضبط ما كنت أفكر فيه."},
        {"en": "Would it be possible to change my order?", "ar": "هل من الممكن تغيير طلبي؟"},
        {"en": "I'm calling to ask about the appointment.", "ar": "أتصل لأسأل عن الموعد."},
        {"en": "Honestly, I'm not too sure about that.", "ar": "بصراحة، لست متأكداً من ذلك."},
        {"en": "Let me get back to you on that.", "ar": "دعني أعود إليك بخصوص ذلك."},
        {"en": "It's been a while since we last met.", "ar": "لقد مضى وقت منذ آخر لقاء لنا."},
        {"en": "I didn't quite catch what you said.", "ar": "لم أفهم تماماً ما قلته."},
        {"en": "Could we go over the details again?", "ar": "هل يمكننا مراجعة التفاصيل مرة أخرى؟"},
        {"en": "In my opinion, this is the better choice.", "ar": "في رأيي، هذا هو الخيار الأفضل."},
        {"en": "I'm looking forward to hearing from you.", "ar": "أتطلع إلى الرد منك."},
        {"en": "Do you have any recommendations?", "ar": "هل لديك أي توصيات؟"},
        {"en": "I'll take care of it right away.", "ar": "سأتولى الأمر على الفور."},
        {"en": "There's something I'd like to discuss.", "ar": "هناك أمر أود مناقشته."},
        {"en": "That makes a lot of sense.", "ar": "هذا منطقي جداً."},
        {"en": "Let's stay in touch.", "ar": "لنبقَ على تواصل."},
        {"en": "I'm not entirely convinced by that argument.", "ar": "لست مقتنعاً تماماً بهذه الحجة."},
        {"en": "Would you mind repeating the question?", "ar": "هل تمانع في إعادة السؤال؟"},
        {"en": "I've been meaning to ask you about that.", "ar": "كنت أنوي سؤالك عن ذلك."},
        {"en": "That's a fair assessment of the situation.", "ar": "هذا تقييم عادل للموقف."},
        {"en": "I'd appreciate it if you could confirm by Friday.", "ar": "أقدّر لو تستطيع التأكيد بحلول يوم الجمعة."},
        {"en": "We seem to have a difference of opinion here.", "ar": "يبدو أن لدينا اختلافاً في الرأي هنا."},
        {"en": "I'll need some time to think it over.", "ar": "سأحتاج بعض الوقت للتفكير في الأمر."},
        {"en": "Could you walk me through the process?", "ar": "هل يمكنك شرح العملية لي خطوة بخطوة؟"},
        {"en": "I'm a little concerned about the deadline.", "ar": "أنا قلق قليلاً بشأن الموعد النهائي."},
        {"en": "Let's try to find a middle ground.", "ar": "لنحاول إيجاد حل وسط."},
        {"en": "I wasn't expecting that response, to be honest.", "ar": "لم أكن أتوقع هذا الرد بصراحة."},
        {"en": "It's not quite what I had in mind.", "ar": "ليس هذا بالضبط ما كنت أفكر فيه."},
        {"en": "I'd like to get a second opinion on this.", "ar": "أود الحصول على رأي ثانٍ في هذا الأمر."},
        {"en": "We're running a bit behind schedule.", "ar": "نحن متأخرون قليلاً عن الجدول الزمني."},
        {"en": "Let me double-check that for you.", "ar": "دعني أتحقق من ذلك مرة أخرى من أجلك."},
        {"en": "I don't want to jump to conclusions.", "ar": "لا أريد التسرع في الاستنتاجات."},
        {"en": "That's a valid concern, actually.", "ar": "هذا قلق مشروع في الواقع."},
        {"en": "I was under the impression that it was finished.", "ar": "كان انطباعي أن الأمر قد انتهى."},
        {"en": "Let's touch base again next week.", "ar": "لنتواصل مرة أخرى الأسبوع القادم."},
        {"en": "I think we're on the right track.", "ar": "أعتقد أننا على المسار الصحيح."},
        {"en": "Can you elaborate on that point a bit more?", "ar": "هل يمكنك التوسع في هذه النقطة أكثر؟"},
        {"en": "It's a trade-off between cost and quality.", "ar": "الأمر مفاضلة بين التكلفة والجودة."},
        {"en": "I'd like to bring up something else, if that's okay.", "ar": "أود طرح موضوع آخر، إذا كان ذلك مناسباً."},
        {"en": "That decision wasn't entirely up to me.", "ar": "ذلك القرار لم يكن بيدي بالكامل."},
        {"en": "I'll follow up with an email afterward.", "ar": "سأتابع الأمر برسالة إلكترونية لاحقاً."},
        {"en": "We should weigh our options carefully.", "ar": "يجب أن نزن خياراتنا بعناية."},
        {"en": "I can see both sides of the argument.", "ar": "أستطيع رؤية جانبي الحجة."},
        {"en": "Let's not rush into a decision.", "ar": "لنتجنب التسرع في اتخاذ قرار."},
        {"en": "I was pleasantly surprised by the outcome.", "ar": "فوجئت بسرور بالنتيجة."},
        {"en": "It caught me a bit off guard, honestly.", "ar": "فاجأني الأمر بصراحة."},
        {"en": "I have a few reservations about the plan.", "ar": "لدي بعض التحفظات على الخطة."},
        {"en": "Let's set some clear expectations from the start.", "ar": "لنضع توقعات واضحة منذ البداية."},
        {"en": "I'd rather we handled this in person.", "ar": "أفضّل أن نتعامل مع هذا وجهاً لوجه."},
        {"en": "That's roughly what I was picturing too.", "ar": "هذا تقريباً ما كنت أتخيله أيضاً."},
        {"en": "I don't think that's entirely fair to them.", "ar": "لا أعتقد أن هذا عادل تماماً بالنسبة لهم."},
        {"en": "We need to iron out a few details first.", "ar": "نحتاج لتسوية بعض التفاصيل أولاً."},
        {"en": "I'm open to other suggestions.", "ar": "أنا منفتح على اقتراحات أخرى."},
        {"en": "Let's revisit this once we have more information.", "ar": "لنعد لهذا الموضوع بعد أن نحصل على معلومات أكثر."},
        {"en": "I hadn't considered it from that angle before.", "ar": "لم أفكر بالأمر من هذه الزاوية من قبل."},
        {"en": "It's a bit of a grey area, to be honest.", "ar": "الأمر منطقة رمادية إلى حد ما بصراحة."},
        {"en": "I'll need your sign-off before we proceed.", "ar": "سأحتاج موافقتك قبل أن نتابع."},
        {"en": "There's been a slight change of plans.", "ar": "حدث تغيير طفيف في الخطط."},
        {"en": "I'm trying to keep an open mind about it.", "ar": "أحاول أن أبقي عقلي منفتحاً حيال ذلك."},
        {"en": "We should probably loop in the rest of the team.", "ar": "ربما يجب أن نُشرك بقية الفريق."},
        {"en": "That's slightly outside my area of expertise.", "ar": "هذا خارج مجال خبرتي قليلاً."},
        {"en": "I want to make sure we're on the same page.", "ar": "أريد التأكد من أننا متفقون."},
        {"en": "It's worth double-checking before we commit.", "ar": "يستحق الأمر التحقق مرة أخرى قبل أن نلتزم."},
        {"en": "I appreciate your patience with all of this.", "ar": "أقدّر صبرك على كل هذا."},
        {"en": "Let's not lose momentum on this project.", "ar": "لنحافظ على الزخم في هذا المشروع."},
        {"en": "I think there's room for improvement here.", "ar": "أعتقد أن هناك مجالاً للتحسين هنا."},
        {"en": "That's a reasonable compromise, I think.", "ar": "أعتقد أن هذا حل وسط معقول."},
        {"en": "I'd like some clarification on the next steps.", "ar": "أود توضيحاً بشأن الخطوات القادمة."},
        {"en": "We're still ironing out a few kinks.", "ar": "لا زلنا نحل بعض المشاكل الصغيرة."},
        {"en": "I don't want to speak out of turn here.", "ar": "لا أريد التحدث في غير وقتي هنا."},
        {"en": "That's putting it mildly, honestly.", "ar": "هذا وصف مخفف للأمر بصراحة."},
        {"en": "Let's give it a bit more time before deciding.", "ar": "لنمنح الأمر مزيداً من الوقت قبل أن نقرر."},
        {"en": "I'm inclined to agree with you on that.", "ar": "أميل للموافقة معك على ذلك."},
        {"en": "It's not something I take lightly.", "ar": "ليس أمراً آخذه ببساطة."},
        {"en": "We should set a realistic timeline.", "ar": "يجب أن نضع جدولاً زمنياً واقعياً."},
        {"en": "I hope this doesn't come across the wrong way.", "ar": "أتمنى ألا يُفهم هذا بشكل خاطئ."},
        {"en": "Let's keep the lines of communication open.", "ar": "لنبقِ قنوات التواصل مفتوحة."},
        {"en": "I'll draft something and send it your way.", "ar": "سأعد مسودة وأرسلها لك."},
        {"en": "That's a fairly common misconception, actually.", "ar": "هذا في الواقع سوء فهم شائع إلى حد ما."},
        {"en": "We might need to adjust our approach slightly.", "ar": "قد نحتاج لتعديل نهجنا قليلاً."},
        {"en": "I want to be upfront about the challenges.", "ar": "أريد أن أكون صريحاً بشأن التحديات."},
        {"en": "Let's not overthink this too much.", "ar": "لنتجنب التفكير المفرط في هذا."},
        {"en": "I could really use your input on this.", "ar": "سأستفيد كثيراً من رأيك في هذا الأمر."},
        {"en": "That's an interesting way of looking at it.", "ar": "هذه طريقة مثيرة للاهتمام للنظر في الأمر."},
        {"en": "I think we've covered the main points.", "ar": "أعتقد أننا غطينا النقاط الرئيسية."},
        {"en": "Let's park that idea for now and move on.", "ar": "لنؤجل هذه الفكرة الآن ونتابع."},
        {"en": "I'll need to run this by my manager first.", "ar": "سأحتاج لعرض هذا على مديري أولاً."},
        {"en": "That timeline seems a bit tight, honestly.", "ar": "يبدو هذا الجدول الزمني ضيقاً بصراحة."},
        {"en": "I'm fairly confident this will work out.", "ar": "أنا واثق إلى حد كبير أن هذا سينجح."},
        {"en": "Let's not make any assumptions just yet.", "ar": "لنتجنب أي افتراضات في الوقت الحالي."},
        {"en": "I owe you an apology for that misunderstanding.", "ar": "أدين لك باعتذار عن سوء الفهم ذاك."},
        {"en": "We should probably get a written agreement.", "ar": "ربما يجب أن نحصل على اتفاق مكتوب."},
        {"en": "I've had a change of heart about it.", "ar": "غيّرت رأيي بشأن ذلك."},
        {"en": "That's a fairly bold claim to make.", "ar": "هذا ادعاء جريء إلى حد ما."},
        {"en": "Let's not put all our eggs in one basket.", "ar": "لنتجنب المخاطرة بكل شيء في مكان واحد."},
        {"en": "I'll take that under advisement, thank you.", "ar": "سآخذ ذلك بعين الاعتبار، شكراً لك."},
        {"en": "We're all working toward the same goal here.", "ar": "نحن جميعاً نعمل نحو نفس الهدف هنا."},
        {"en": "I think it's best if we table this discussion.", "ar": "أعتقد أنه من الأفضل تأجيل هذا النقاش."},
        {"en": "That's a reasonable expectation to have.", "ar": "هذا توقع معقول أن نحمله."},
        {"en": "Let's make sure everyone's voice is heard.", "ar": "لنتأكد من أن صوت الجميع مسموع."},
        {"en": "I'm a little skeptical about that claim.", "ar": "أنا متشكك قليلاً في هذا الادعاء."},
        {"en": "We appreciate your flexibility on this matter.", "ar": "نقدّر مرونتك في هذا الأمر."},
        {"en": "I think we should proceed with caution.", "ar": "أعتقد أننا يجب أن نمضي بحذر."},
    ],
    "Advanced": [
        {"en": "I'd argue that the benefits outweigh the risks.", "ar": "أرى أن الفوائد تفوق المخاطر."},
        {"en": "To be perfectly honest, I have mixed feelings about it.", "ar": "لأكون صادقاً تماماً، لدي مشاعر متضاربة حيال ذلك."},
        {"en": "That's a compelling point, but I see it differently.", "ar": "هذه نقطة مقنعة، لكنني أراها بشكل مختلف."},
        {"en": "Let's not jump to conclusions just yet.", "ar": "دعنا لا نتسرع في الاستنتاجات بعد."},
        {"en": "I'd like to play devil's advocate for a moment.", "ar": "أود أن أطرح الرأي المعارض للحظة."},
        {"en": "There's more to this than meets the eye.", "ar": "الأمر أعقد مما يبدو عليه."},
        {"en": "I can see where you're coming from.", "ar": "أفهم وجهة نظرك."},
        {"en": "We'll have to agree to disagree on that.", "ar": "سيتعين علينا أن نتفق على أن نختلف في ذلك."},
        {"en": "Let me put it another way.", "ar": "دعني أصيغها بطريقة أخرى."},
        {"en": "That's easier said than done.", "ar": "قول ذلك أسهل من فعله."},
        {"en": "I'm inclined to think we should wait.", "ar": "أميل إلى الاعتقاد بأنه ينبغي أن ننتظر."},
        {"en": "On the whole, it went better than expected.", "ar": "بشكل عام، سار الأمر أفضل مما كان متوقعاً."},
        {"en": "Let's weigh the pros and cons carefully.", "ar": "لنزن الإيجابيات والسلبيات بعناية."},
        {"en": "I don't want to overstate the case, but it's serious.", "ar": "لا أريد المبالغة، لكن الأمر جدي."},
        {"en": "That aligns closely with what I had in mind.", "ar": "هذا يتوافق تماماً مع ما كان في ذهني."},
        {"en": "With all due respect, I have to disagree.", "ar": "مع كامل احترامي، لا بد أن أختلف."},
        {"en": "It's a delicate matter, so let's tread carefully.", "ar": "إنها مسألة حساسة، لذا لنتعامل بحذر."},
        {"en": "I'd hate to jump the gun on this.", "ar": "لا أود التسرع في هذا الأمر."},
        {"en": "Let's circle back to that later.", "ar": "لنعد إلى ذلك لاحقاً."},
        {"en": "In the grand scheme of things, it's minor.", "ar": "في الصورة الأكبر، إنه أمر بسيط."},
        {"en": "I'm cautiously optimistic about the outcome.", "ar": "أنا متفائل بحذر بشأن النتيجة."},
        {"en": "That raises an interesting question.", "ar": "هذا يطرح سؤالاً مثيراً للاهتمام."},
        {"en": "Let's give credit where credit is due.", "ar": "لنعطِ الفضل لمن يستحقه."},
        {"en": "I wouldn't go that far, personally.", "ar": "شخصياً، لن أذهب إلى هذا الحد."},
        {"en": "We're on the same page, then.", "ar": "إذاً نحن متفقون."},
        {"en": "It's worth taking with a grain of salt.", "ar": "من الأفضل أخذه بتحفظ."},
        {"en": "Let's not lose sight of the bigger picture.", "ar": "لنبقِ الصورة الأكبر نصب أعيننا."},
        {"en": "I'll go out on a limb and say it'll work.", "ar": "سأخاطر وأقول إنه سينجح."},
        {"en": "That's precisely the crux of the matter.", "ar": "هذا هو جوهر المسألة بالضبط."},
        {"en": "All things considered, I'm satisfied.", "ar": "بعد أخذ كل شيء بعين الاعتبار، أنا راضٍ."},
        {"en": "It's a nuanced issue with no easy answers.", "ar": "إنها قضية دقيقة بلا إجابات سهلة."},
        {"en": "I'd be remiss not to mention the risks involved.", "ar": "سأكون مقصراً إن لم أذكر المخاطر المترتبة."},
        {"en": "That's something of a double-edged sword.", "ar": "هذا نوعاً ما سلاح ذو حدين."},
        {"en": "Let's not conflate two separate issues here.", "ar": "لنتجنب الخلط بين قضيتين منفصلتين هنا."},
        {"en": "I find myself torn between the two options.", "ar": "أجد نفسي متردداً بين الخيارين."},
        {"en": "It's a moot point at this stage, frankly.", "ar": "إنها نقطة غير ذات أهمية في هذه المرحلة بصراحة."},
        {"en": "We ought to tread lightly given the circumstances.", "ar": "يجب أن نتصرف بحذر نظراً للظروف."},
        {"en": "That's a rather sweeping generalization, isn't it?", "ar": "هذا تعميم شامل إلى حد ما، أليس كذلك؟"},
        {"en": "I'm not entirely sold on that premise.", "ar": "لست مقتنعاً تماماً بتلك الفرضية."},
        {"en": "Let's unpack that a little further.", "ar": "دعنا نفصّل ذلك أكثر."},
        {"en": "It stands to reason that costs would rise.", "ar": "من المنطقي أن ترتفع التكاليف."},
        {"en": "I'd stop short of calling it a failure.", "ar": "لن أذهب إلى حد وصفه بالفشل."},
        {"en": "There's a certain irony in that outcome.", "ar": "هناك مفارقة معينة في تلك النتيجة."},
        {"en": "We should be wary of drawing hasty conclusions.", "ar": "يجب أن نحذر من استخلاص استنتاجات متسرعة."},
        {"en": "That argument doesn't quite hold water.", "ar": "هذه الحجة لا تصمد فعلياً."},
        {"en": "I'm playing catch-up on the details, admittedly.", "ar": "أنا أحاول اللحاق بالتفاصيل، بصراحة."},
        {"en": "It's a fine line between confidence and arrogance.", "ar": "هناك خط رفيع بين الثقة والغرور."},
        {"en": "Let's not lose sleep over something so minor.", "ar": "لنتجنب القلق الزائد بشأن أمر بسيط كهذا."},
        {"en": "I'd venture to say it's the best option available.", "ar": "أجرؤ على القول إنه أفضل خيار متاح."},
        {"en": "That's a slippery slope, if you ask me.", "ar": "هذا منحدر زلق، إن سألتني."},
        {"en": "We're at something of a crossroads here.", "ar": "نحن في مفترق طرق نوعاً ما هنا."},
        {"en": "It's easy to lose perspective in situations like this.", "ar": "من السهل فقدان المنظور الصحيح في مواقف كهذه."},
        {"en": "I'll concede that point, but only partially.", "ar": "سأسلّم بتلك النقطة، لكن جزئياً فقط."},
        {"en": "That's the elephant in the room, isn't it?", "ar": "هذا هو الأمر الذي يتجاهله الجميع، أليس كذلك؟"},
        {"en": "Let's not beat around the bush any longer.", "ar": "لنتوقف عن المراوغة بعد الآن."},
        {"en": "I have a nagging feeling something's off.", "ar": "لدي شعور مزعج بأن هناك شيئاً خاطئاً."},
        {"en": "It's worth noting the broader implications here.", "ar": "يستحق الأمر ملاحظة التبعات الأوسع هنا."},
        {"en": "We're splitting hairs over a minor detail.", "ar": "نحن نتجادل حول تفصيلة بسيطة."},
        {"en": "That's a bold move, all things considered.", "ar": "هذه خطوة جريئة بعد أخذ كل شيء بعين الاعتبار."},
        {"en": "I'd argue the merits outweigh the drawbacks.", "ar": "أرى أن المزايا تفوق العيوب."},
        {"en": "Let's not put the cart before the horse.", "ar": "لنتجنب البدء بالخطوة الخاطئة."},
        {"en": "It's a self-fulfilling prophecy at this point.", "ar": "أصبحت نبوءة تحقق نفسها في هذه المرحلة."},
        {"en": "I stand corrected on that particular point.", "ar": "أصحح رأيي بشأن هذه النقطة تحديداً."},
        {"en": "That's tantamount to admitting defeat, isn't it?", "ar": "هذا أشبه بالاعتراف بالهزيمة، أليس كذلك؟"},
        {"en": "We need to read between the lines here.", "ar": "نحتاج لقراءة ما بين السطور هنا."},
        {"en": "It's a delicate balancing act, to say the least.", "ar": "إنها عملية موازنة دقيقة، على أقل تقدير."},
        {"en": "I'd hesitate to draw a direct correlation.", "ar": "سأتردد في استنتاج علاقة مباشرة."},
        {"en": "That's easier said than implemented, frankly.", "ar": "قول هذا أسهل من تطبيقه بصراحة."},
        {"en": "Let's not throw the baby out with the bathwater.", "ar": "لنتجنب التخلص من الجيد مع السيء."},
        {"en": "It remains to be seen how this will play out.", "ar": "لا يزال يتعين رؤية كيف ستتطور الأمور."},
        {"en": "I take that with a healthy dose of skepticism.", "ar": "آخذ ذلك بجرعة صحية من التشكك."},
        {"en": "That's a textbook example of overreach.", "ar": "هذا مثال نموذجي على تجاوز الحدود."},
        {"en": "We should hedge our bets on this one.", "ar": "يجب أن نتحوط في رهاناتنا على هذا الأمر."},
        {"en": "It's a matter of perspective, ultimately.", "ar": "الأمر مسألة منظور في النهاية."},
        {"en": "I'd be lying if I said it didn't concern me.", "ar": "سأكون كاذباً إن قلت إنه لا يقلقني."},
        {"en": "That's a rather generous interpretation of events.", "ar": "هذا تفسير سخي إلى حد ما للأحداث."},
        {"en": "Let's not get ahead of ourselves just yet.", "ar": "لنتجنب التسرع في الاستنتاجات الآن."},
        {"en": "It's a calculated risk, but a risk nonetheless.", "ar": "إنها مخاطرة محسوبة، لكنها مخاطرة رغم ذلك."},
        {"en": "I'd rather err on the side of caution here.", "ar": "أفضّل الميل نحو الحذر هنا."},
        {"en": "That's a false dichotomy, if you think about it.", "ar": "هذا تناقض زائف إن فكرت في الأمر."},
        {"en": "We're treading into uncharted territory here.", "ar": "نحن ندخل منطقة مجهولة هنا."},
        {"en": "It's a subtle distinction, but an important one.", "ar": "إنه تمييز دقيق، لكنه مهم."},
        {"en": "I wouldn't read too much into it, honestly.", "ar": "لن أبالغ في تفسير الأمر بصراحة."},
        {"en": "That's precisely why the nuance matters here.", "ar": "هذا بالضبط سبب أهمية الدقة هنا."},
        {"en": "Let's not paint everyone with the same brush.", "ar": "لنتجنب التعميم على الجميع بنفس الطريقة."},
        {"en": "It's a bit of a Catch-22 situation, really.", "ar": "إنه موقف متناقض حقاً."},
        {"en": "I'll reserve judgment until I see the full picture.", "ar": "سأمتنع عن إصدار الحكم حتى أرى الصورة كاملة."},
        {"en": "That's a slippery use of statistics, frankly.", "ar": "هذا استخدام مضلل للإحصائيات بصراحة."},
        {"en": "We should approach this with a degree of humility.", "ar": "يجب أن نتعامل مع هذا بقدر من التواضع."},
        {"en": "It's a matter of when, not if, at this point.", "ar": "المسألة مسألة وقت وليس احتمالاً في هذه المرحلة."},
        {"en": "I'd sooner trust the data than the anecdotes.", "ar": "أثق بالبيانات أكثر من القصص الفردية."},
        {"en": "That's a compelling case, but not an airtight one.", "ar": "هذه حجة مقنعة، لكنها ليست محكمة تماماً."},
        {"en": "Let's not conflate correlation with causation.", "ar": "لنتجنب الخلط بين الارتباط والسببية."},
        {"en": "It's worth playing devil's advocate here, briefly.", "ar": "يستحق الأمر تبني الرأي المعارض هنا لفترة وجيزة."},
        {"en": "I'd caution against reading too much symbolism into it.", "ar": "أحذر من المبالغة في قراءة الرمزية في الأمر."},
        {"en": "That's a fairly reductive way of framing it.", "ar": "هذه طريقة مبسطة إلى حد ما لصياغة الأمر."},
        {"en": "We're essentially debating semantics at this point.", "ar": "نحن نتجادل حول المصطلحات أساساً في هذه المرحلة."},
        {"en": "It's a question of trade-offs, as with most things.", "ar": "الأمر مسألة مفاضلات، كما هو الحال في معظم الأمور."},
        {"en": "I'd push back gently on that assumption.", "ar": "سأعترض برفق على هذا الافتراض."},
        {"en": "That's a fairly charitable reading of the situation.", "ar": "هذه قراءة متسامحة إلى حد ما للموقف."},
        {"en": "Let's not lose the forest for the trees here.", "ar": "لنتجنب الانشغال بالتفاصيل عن الصورة الكاملة هنا."},
        {"en": "It's an uphill battle, but not an impossible one.", "ar": "إنها معركة شاقة، لكنها ليست مستحيلة."},
        {"en": "I suspect there's more nuance than the headline suggests.", "ar": "أظن أن هناك تفاصيل أدق مما يوحي به العنوان."},
        {"en": "That's a rather cynical take, if I'm honest.", "ar": "هذا رأي متشائم إلى حد ما، إن كنت صريحاً."},
        {"en": "We should probably stress-test that assumption.", "ar": "ربما يجب أن نختبر هذا الافتراض بشكل مكثف."},
        {"en": "It's a fine distinction, but it matters in practice.", "ar": "إنه تمييز دقيق، لكنه مهم من الناحية العملية."},
        {"en": "I wouldn't stake my reputation on that claim.", "ar": "لن أراهن بسمعتي على هذا الادعاء."},
        {"en": "That's a pragmatic, if somewhat cautious, approach.", "ar": "هذا نهج عملي، وإن كان حذراً إلى حد ما."},
        {"en": "Let's not underestimate the human element here.", "ar": "لنتجنب الاستهانة بالعنصر البشري هنا."},
        {"en": "It's a marginal gain, but a gain nonetheless.", "ar": "إنه مكسب هامشي، لكنه مكسب رغم ذلك."},
        {"en": "I'd frame it as an opportunity rather than a setback.", "ar": "سأصيغه كفرصة وليس كنكسة."},
        {"en": "That's precisely the kind of ambiguity we should avoid.", "ar": "هذا بالضبط نوع الغموض الذي يجب أن نتجنبه."},
        {"en": "We're better served focusing on what we can control.", "ar": "من الأفضل أن نركز على ما يمكننا التحكم به."},
        {"en": "It's a reasonable middle ground, all told.", "ar": "إنه حل وسط معقول، في المجمل."},
    ],
}


# ----------------------------------------------------------------------
# 2) SCRIPTED CONVERSATIONS — branching dialogues, no API
# ----------------------------------------------------------------------
# Each conversation is a small tree of NODES. The learner reads/hears what
# the character says, then chooses one of several replies (they can also
# say it out loud — speech is scored). Each reply leads to the next node.
#
# Node shape:
#   "id":   unique node id within this conversation
#   "npc":  {"en": what the character says, "ar": translation}
#   "replies": [ {"en": learner line, "ar": translation, "goto": next_node_id}, ... ]
#   A node with "end": True (and no replies) finishes the conversation.
#
# This is deterministic: same choices, same path. No AI, always works.

def _n(id, npc_en, npc_ar, replies=None, end=False):
    node = {"id": id, "npc": {"en": npc_en, "ar": npc_ar}}
    if replies:
        node["replies"] = [{"en": r[0], "ar": r[1], "goto": r[2]} for r in replies]
    if end:
        node["end"] = True
    return node


CONVERSATIONS = [
    {
        "id": "cafe",
        "title": "Order at a café",
        "level": "Beginner",
        "emoji": "☕",
        "setting": "A busy café. You're at the counter and the barista greets you.",
        "goal": "Order a drink, ask the price, and pay.",
        "is_premium": False,
        "start": "n1",
        "nodes": [
            _n("n1", "Hi there! What can I get for you today?",
               "مرحباً! ماذا يمكنني أن أحضر لك اليوم؟",
               [("Hi, could I have a coffee, please?", "مرحباً، هل يمكنني الحصول على قهوة من فضلك؟", "n2a"),
                ("Hello. What do you recommend?", "مرحباً. بماذا تنصح؟", "n2b")]),
            _n("n2a", "Great choice! Hot or iced?",
               "اختيار رائع! ساخنة أم مثلجة؟",
               [("Hot, please. It's a bit cold outside.", "ساخنة من فضلك. الجو بارد قليلاً بالخارج.", "n3")]),
            _n("n2b", "Our cappuccino is really popular — want to try one?",
               "الكابتشينو لدينا مشهور جداً — هل تريد تجربته؟",
               [("Sure, let's go with that.", "بالتأكيد، لنجرب ذلك.", "n3")]),
            _n("n3", "Perfect. What size — small or large?",
               "ممتاز. أي حجم — صغير أم كبير؟",
               [("A large one, please.", "كبير من فضلك.", "n4a"),
                ("Small is fine, thanks.", "صغير جيد، شكراً.", "n4b")]),
            _n("n4a", "Good choice, large will keep you going all morning.",
               "اختيار جيد، الكبير سيكفيك طوال الصباح.",
               [("Ha, exactly what I need today.", "بالضبط ما أحتاجه اليوم.", "n5")]),
            _n("n4b", "No problem, small it is.",
               "لا مشكلة، صغير إذاً.",
               [("Thanks, that's plenty for me.", "شكراً، هذا يكفيني.", "n5")]),
            _n("n5", "Would you like anything to eat with that? We have fresh croissants.",
               "هل تريد شيئاً لتأكله معها؟ لدينا كرواسون طازج.",
               [("Sure, I'll take one.", "بالتأكيد، سآخذ واحداً.", "n6"),
                ("No thanks, just the drink.", "لا شكراً، المشروب فقط.", "n6")]),
            _n("n6", "Alright, that comes to three dollars fifty.",
               "حسناً، المجموع ثلاثة دولارات ونصف.",
               [("Can I pay by card?", "هل يمكنني الدفع بالبطاقة؟", "n7a"),
                ("Here's the cash.", "تفضل النقود.", "n7b")]),
            _n("n7a", "Of course, just tap here whenever you're ready.",
               "بالتأكيد، فقط المس هنا عندما تكون جاهزاً.",
               [("Done — thank you!", "تم — شكراً لك!", "n8")]),
            _n("n7b", "Perfect, here's your change.",
               "ممتاز، تفضل الباقي.",
               [("Thank you!", "شكراً لك!", "n8")]),
            _n("n8", "You're welcome! I'll call your name when it's ready.",
               "على الرحب والسعة! سأنادي باسمك عندما يكون جاهزاً.",
               [("Great, I'll wait over there.", "رائع، سأنتظر هناك.", "end")]),
            _n("end", "☕ (A few minutes later) Here's your order — have a lovely day!",
               "☕ (بعد دقائق قليلة) تفضل طلبك — أتمنى لك يوماً جميلاً!", end=True),
        ],
    },
    {
        "id": "directions",
        "title": "You're lost",
        "level": "Beginner",
        "emoji": "🗺️",
        "setting": "A street in a new city. You stop a friendly local to ask for help.",
        "goal": "Ask the way to the train station and how long it takes.",
        "is_premium": False,
        "start": "n1",
        "nodes": [
            _n("n1", "You look a little lost — need a hand?",
               "تبدو تائهاً قليلاً — هل تحتاج مساعدة؟",
               [("Yes, please. How do I get to the train station?", "نعم من فضلك. كيف أصل إلى محطة القطار؟", "n2a"),
                ("Excuse me, is there a pharmacy near here too?", "المعذرة، هل يوجد صيدلية قريبة من هنا أيضاً؟", "n2b")]),
            _n("n2a", "The station? Sure, it's not far from here at all.",
               "المحطة؟ بالتأكيد، ليست بعيدة من هنا على الإطلاق.",
               [("That's good to know.", "هذا جيد أن أعرفه.", "n3")]),
            _n("n2b", "There's one two streets over, and the station is close to it too.",
               "يوجد واحدة بعد شارعين، والمحطة قريبة منها أيضاً.",
               [("Perfect, I need both anyway.", "ممتاز، أحتاج كليهما على أي حال.", "n3")]),
            _n("n3", "Go straight down this street, then turn left at the lights.",
               "امشِ مباشرة في هذا الشارع، ثم انعطف يساراً عند الإشارة.",
               [("Left at the lights, got it.", "يساراً عند الإشارة، فهمت.", "n4a"),
                ("Sorry, could you say that again?", "آسف، هل يمكنك قول ذلك مرة أخرى؟", "n4b")]),
            _n("n4a", "Exactly. You'll see the entrance right in front of you.",
               "بالضبط. سترى المدخل أمامك مباشرة.",
               [("Great, that sounds easy enough.", "رائع، يبدو سهلاً بما فيه الكفاية.", "n5")]),
            _n("n4b", "No problem — straight ahead, then left at the traffic lights.",
               "لا مشكلة — مباشرة إلى الأمام، ثم يساراً عند إشارة المرور.",
               [("Got it now, thank you for repeating that.", "فهمت الآن، شكراً لإعادتك ذلك.", "n5")]),
            _n("n5", "How long does it take to walk, you're probably wondering?",
               "كم يستغرق المشي، ربما تتساءل؟",
               [("Yes, actually — is it far?", "نعم في الواقع — هل هي بعيدة؟", "n6")]),
            _n("n6", "About ten minutes on foot. You can't miss it.",
               "حوالي عشر دقائق سيراً. لن تخطئها.",
               [("Ten minutes, perfect. I have time.", "عشر دقائق، ممتاز. لدي وقت.", "n7")]),
            _n("n7", "If you're in a rush, there's also a bus that stops right there.",
               "إن كنت مستعجلاً، هناك أيضاً حافلة تتوقف هناك مباشرة.",
               [("Good to know, but I'll enjoy the walk.", "جيد أن أعرف، لكنني سأستمتع بالمشي.", "n8")]),
            _n("n8", "Sounds good. Safe travels, wherever you're headed!",
               "يبدو جيداً. رحلة آمنة، أينما كنت متجهاً!",
               [("Thank you, I really appreciate your help.", "شكراً لك، أقدّر مساعدتك حقاً.", "end")]),
            _n("end", "🗺️ (You know the way now. Nicely handled!)",
               "🗺️ (تعرف الطريق الآن. أحسنت التصرف!)", end=True),
        ],
    },
    {
        "id": "interview",
        "title": "Job interview",
        "level": "Intermediate",
        "emoji": "💼",
        "setting": "An interview for a job you want. The manager smiles and begins.",
        "goal": "Introduce yourself, describe your experience, and ask a question.",
        "is_premium": True,
        "start": "n1",
        "nodes": [
            _n("n1", "Thanks for coming in. So, tell me a little about yourself.",
               "شكراً لحضورك. إذاً، أخبرني قليلاً عن نفسك.",
               [("I have three years of experience in this field.", "لدي ثلاث سنوات من الخبرة في هذا المجال.", "n2a"),
                ("I'm a hard worker who enjoys solving problems.", "أنا شخص مجتهد يستمتع بحل المشكلات.", "n2b")]),
            _n("n2a", "Three years — that's solid. What did that role involve?",
               "ثلاث سنوات — هذا جيد. ماذا تضمن ذلك الدور؟",
               [("Mostly managing client projects from start to finish.", "بشكل أساسي إدارة مشاريع العملاء من البداية للنهاية.", "n3")]),
            _n("n2b", "I like that. Can you give me an example of a problem you solved?",
               "يعجبني ذلك. هل يمكنك إعطائي مثالاً على مشكلة حللتها؟",
               [("Sure — I once fixed a scheduling conflict that saved the team a week.", "بالتأكيد — حللت مرة تعارضاً في الجدولة وفّر على الفريق أسبوعاً.", "n3")]),
            _n("n3", "Impressive. What would you say is your biggest strength?",
               "مثير للإعجاب. ما الذي تعتبره أكبر نقطة قوة لديك؟",
               [("I stay calm under pressure.", "أبقى هادئاً تحت الضغط.", "n4a"),
                ("I learn new things quickly.", "أتعلم أشياء جديدة بسرعة.", "n4b")]),
            _n("n4a", "That's valuable here — things get busy fast sometimes.",
               "هذا قيّم هنا — تصبح الأمور مزدحمة بسرعة أحياناً.",
               [("I actually enjoy that kind of pace.", "أستمتع في الواقع بهذا النوع من الوتيرة.", "n5")]),
            _n("n4b", "Good, because this role involves a lot of new tools.",
               "جيد، لأن هذا الدور يتضمن الكثير من الأدوات الجديدة.",
               [("I'm looking forward to that, honestly.", "أتطلع لذلك بصراحة.", "n5")]),
            _n("n5", "And on the flip side — what's something you're working to improve?",
               "وفي المقابل — ما الشيء الذي تعمل على تحسينه؟",
               [("I'm working on delegating more instead of doing everything myself.", "أعمل على تفويض المهام أكثر بدلاً من فعل كل شيء بنفسي.", "n6")]),
            _n("n6", "That's a really self-aware answer. Good to hear.",
               "هذه إجابة واعية جداً بذاتها. جيد أن أسمعها.",
               [("Thank you, I try to be honest about it.", "شكراً، أحاول أن أكون صادقاً حيال ذلك.", "n7")]),
            _n("n7", "Do you have any questions for me before we wrap up?",
               "هل لديك أي أسئلة لي قبل أن ننهي؟",
               [("Yes — what does a typical day look like here?", "نعم — كيف يبدو اليوم المعتاد هنا؟", "n8"),
                ("Could you tell me more about the team?", "هل يمكنك إخباري أكثر عن الفريق؟", "n8")]),
            _n("n8", "Great question. I think you'd fit in well here. We'll be in touch soon!",
               "سؤال رائع. أعتقد أنك ستنسجم جيداً هنا. سنتواصل معك قريباً!",
               [("Thank you for your time today.", "شكراً على وقتك اليوم.", "end")]),
            _n("end", "💼 (Strong interview. You represented yourself well!)",
               "💼 (مقابلة قوية. قدمت نفسك بشكل جيد!)", end=True),
        ],
    },
    {
        "id": "complaint",
        "title": "Something went wrong",
        "level": "Intermediate",
        "emoji": "📦",
        "setting": "A shop. The item you bought last week is broken and you want it sorted.",
        "goal": "Explain the problem, say what you want, and reach an agreement.",
        "is_premium": True,
        "start": "n1",
        "nodes": [
            _n("n1", "Hi, how can I help you today?",
               "مرحباً، كيف يمكنني مساعدتك اليوم؟",
               [("There's a problem with something I bought here.", "هناك مشكلة في شيء اشتريته من هنا.", "n2a"),
                ("I'd like to return a faulty item.", "أود إرجاع منتج معيب.", "n2b")]),
            _n("n2a", "Oh, I'm sorry to hear that. What seems to be the issue?",
               "أوه، يؤسفني سماع ذلك. ما هي المشكلة؟",
               [("It stopped working after two days.", "توقف عن العمل بعد يومين.", "n3")]),
            _n("n2b", "No problem, do you have the receipt with you?",
               "لا مشكلة، هل الإيصال معك؟",
               [("Yes, right here.", "نعم، تفضل.", "n3")]),
            _n("n3", "Thanks. Can you tell me exactly what went wrong?",
               "شكراً. هل يمكنك إخباري بالضبط ما الذي حدث؟",
               [("It was broken when I opened the box.", "كان مكسوراً عندما فتحت الصندوق.", "n4a"),
                ("It just stopped turning on one day.", "توقف فجأة عن التشغيل ذات يوم.", "n4b")]),
            _n("n4a", "That shouldn't happen — I apologize for the inconvenience.",
               "لا يجب أن يحدث هذا — أعتذر عن الإزعاج.",
               [("Thank you, I appreciate that.", "شكراً، أقدّر ذلك.", "n5")]),
            _n("n4b", "That's strange, it might be a manufacturing fault.",
               "هذا غريب، قد يكون عيباً في التصنيع.",
               [("That's what I thought too.", "هذا ما ظننته أيضاً.", "n5")]),
            _n("n5", "I understand. Would you like a refund or a replacement?",
               "أفهم. هل تريد استرداد المبلغ أم استبدالاً؟",
               [("A replacement would be great, thank you.", "الاستبدال سيكون رائعاً، شكراً.", "n6a"),
                ("I'd prefer a refund, please.", "أفضّل استرداد المبلغ من فضلك.", "n6b")]),
            _n("n6a", "Sure thing, let me check if we have one in stock.",
               "بالتأكيد، دعني أتحقق إن كان لدينا واحد بالمخزون.",
               [("Take your time, I'll wait.", "خذ وقتك، سأنتظر.", "n7")]),
            _n("n6b", "That's fine, I can process that back to your card.",
               "هذا جيد، يمكنني إعادته إلى بطاقتك.",
               [("Thank you, that works for me.", "شكراً، هذا مناسب لي.", "n7")]),
            _n("n7", "All sorted. Is there anything else I can help with today?",
               "تم كل شيء. هل هناك شيء آخر يمكنني مساعدتك به اليوم؟",
               [("No, that's everything. Thanks for your help.", "لا، هذا كل شيء. شكراً على مساعدتك.", "end")]),
            _n("end", "📦 (Problem solved, calmly and politely. Well done!)",
               "📦 (تم حل المشكلة بهدوء وأدب. أحسنت!)", end=True),
        ],
    },
    {
        "id": "smalltalk",
        "title": "Small talk at an event",
        "level": "Advanced",
        "emoji": "🎤",
        "setting": "A coffee break at a conference. Someone standing nearby turns to you.",
        "goal": "Start a conversation, find common ground, and end it politely.",
        "is_premium": True,
        "start": "n1",
        "nodes": [
            _n("n1", "Quite a turnout today, isn't it? Is this your first time here?",
               "حضور كبير اليوم، أليس كذلك؟ هل هذه أول مرة لك هنا؟",
               [("It is, actually. What about you?", "نعم في الواقع. وأنت؟", "n2a"),
                ("No, I came last year too. It's always worth it.", "لا، حضرت العام الماضي أيضاً. يستحق الحضور دائماً.", "n2b")]),
            _n("n2a", "I've been a few times myself. It gets better every year.",
               "حضرت عدة مرات بنفسي. تتحسن كل عام.",
               [("Good to know — I'll definitely come back then.", "جيد أن أعرف — سأعود بالتأكيد إذاً.", "n3")]),
            _n("n2b", "Same here. The talks this year have been especially good.",
               "وأنا كذلك. كانت المحاضرات هذا العام جيدة بشكل خاص.",
               [("I agree, the morning session was excellent.", "أتفق، كانت جلسة الصباح ممتازة.", "n3")]),
            _n("n3", "So, what field are you in?",
               "إذاً، في أي مجال تعمل؟",
               [("I work in research. And you?", "أعمل في البحث العلمي. وأنت؟", "n4a"),
                ("I'm in education. How about yourself?", "أعمل في التعليم. وماذا عنك؟", "n4b")]),
            _n("n4a", "Oh, interesting — I actually collaborate with researchers often.",
               "أوه، مثير للاهتمام — أتعاون مع باحثين غالباً في الواقع.",
               [("Small world. What's your side of it?", "عالم صغير. ما هو دورك في ذلك؟", "n5")]),
            _n("n4b", "That's great — I actually started out as a teacher myself.",
               "هذا رائع — بدأت في الواقع كمعلم بنفسي.",
               [("Really? What made you switch fields?", "حقاً؟ ما الذي جعلك تغيّر المجال؟", "n5")]),
            _n("n5", "It's a long story, but I ended up in a related field eventually.",
               "إنها قصة طويلة، لكنني انتهى بي المطاف في مجال ذي صلة في النهاية.",
               [("That happens more often than people think.", "يحدث ذلك أكثر مما يعتقد الناس.", "n6")]),
            _n("n6", "Exactly. Anyway, we might have some overlap worth exploring.",
               "بالضبط. على أي حال، قد يكون بيننا تقاطع يستحق الاستكشاف.",
               [("That would be great to talk about sometime.", "سيكون من الرائع التحدث عن ذلك في وقت ما.", "n7")]),
            _n("n7", "Definitely. Do you have a card, or should we connect online?",
               "بالتأكيد. هل لديك بطاقة، أم يجب أن نتواصل عبر الإنترنت؟",
               [("Here you go — feel free to reach out anytime.", "تفضل — لا تتردد بالتواصل في أي وقت.", "n8")]),
            _n("n8", "Perfect, thank you. It was really nice meeting you.",
               "ممتاز، شكراً لك. كان من الجميل حقاً لقاؤك.",
               [("Likewise — enjoy the rest of the event!", "وأنا كذلك — استمتع ببقية الفعالية!", "end")]),
            _n("end", "🎤 (A natural, confident chat. Exactly how it's done!)",
               "🎤 (محادثة طبيعية وواثقة. هكذا يكون الأمر تماماً!)", end=True),
        ],
    },
    {
        "id": "hotel",
        "title": "Checking into a hotel",
        "level": "Beginner",
        "emoji": "🏨",
        "setting": "You've just arrived at your hotel after a long trip.",
        "goal": "Check in, ask about breakfast, and find your room.",
        "is_premium": True,
        "start": "n1",
        "nodes": [
            _n("n1", "Good evening, welcome! Do you have a reservation?",
               "مساء الخير، أهلاً بك! هل لديك حجز؟",
               [("Yes, it's under the name Ali.", "نعم، تحت اسم علي.", "n2a"),
                ("Yes, I booked online last week.", "نعم، حجزت عبر الإنترنت الأسبوع الماضي.", "n2b")]),
            _n("n2a", "Let me look that up... found it! One room, three nights.",
               "دعني أبحث عن ذلك... وجدته! غرفة واحدة، ثلاث ليالٍ.",
               [("That's right.", "هذا صحيح.", "n3")]),
            _n("n2b", "Ah yes, here it is. Everything looks in order.",
               "آه نعم، ها هو. كل شيء يبدو بترتيب.",
               [("Great, glad it went through okay.", "رائع، سعيد أن الأمر تم بشكل جيد.", "n3")]),
            _n("n3", "Could I see your passport, please?",
               "هل يمكنني رؤية جواز سفرك من فضلك؟",
               [("Of course, here you go.", "بالتأكيد، تفضل.", "n4")]),
            _n("n4", "Perfect. Would you prefer a room with a city view or a garden view?",
               "ممتاز. هل تفضل غرفة بإطلالة على المدينة أم على الحديقة؟",
               [("City view sounds nice.", "إطلالة المدينة تبدو جميلة.", "n5a"),
                ("Garden view, if that's available.", "إطلالة الحديقة، إن كانت متاحة.", "n5b")]),
            _n("n5a", "Great choice, the view from the tenth floor is beautiful at night.",
               "اختيار رائع، الإطلالة من الطابق العاشر جميلة ليلاً.",
               [("Sounds perfect, I'll look forward to that.", "يبدو مثالياً، سأتطلع لذلك.", "n6")]),
            _n("n5b", "Good pick, it's much quieter on that side of the building.",
               "اختيار جيد، أكثر هدوءاً في ذلك الجانب من المبنى.",
               [("That's exactly what I need after the flight.", "هذا بالضبط ما أحتاجه بعد الرحلة.", "n6")]),
            _n("n6", "Here's your key. Room 214, second floor.",
               "تفضل مفتاحك. الغرفة 214، الطابق الثاني.",
               [("Great, thank you. What time is breakfast?", "رائع، شكراً. متى وقت الفطور؟", "n7")]),
            _n("n7", "Breakfast is from seven to ten in the main hall downstairs.",
               "الفطور من السابعة إلى العاشرة في القاعة الرئيسية بالأسفل.",
               [("Perfect. Is there an elevator?", "ممتاز. هل يوجد مصعد؟", "n8")]),
            _n("n8", "Yes, right around the corner. Enjoy your stay!",
               "نعم، خلف الزاوية مباشرة. أتمنى لك إقامة طيبة!",
               [("Thank you very much.", "شكراً جزيلاً.", "end")]),
            _n("end", "🏨 (Smooth check-in — you're all set!)",
               "🏨 (تسجيل وصول سلس — كل شيء جاهز!)", end=True),
        ],
    },
    {
        "id": "doctor",
        "title": "At the doctor's office",
        "level": "Intermediate",
        "emoji": "🩺",
        "setting": "You've had a headache for three days and booked an appointment.",
        "goal": "Describe your symptoms and understand the doctor's advice.",
        "is_premium": True,
        "start": "n1",
        "nodes": [
            _n("n1", "Hi, come on in. What brings you in today?",
               "مرحباً، تفضل بالدخول. ما الذي جاء بك اليوم؟",
               [("I've had a headache for three days now.", "أعاني من صداع منذ ثلاثة أيام الآن.", "n2a"),
                ("I haven't been sleeping well and I feel exhausted.", "لم أنم جيداً وأشعر بالإرهاق.", "n2b")]),
            _n("n2a", "I see. Is it constant, or does it come and go?",
               "أفهم. هل هو مستمر أم يأتي ويذهب؟",
               [("It comes and goes, mostly in the afternoon.", "يأتي ويذهب، غالباً في فترة بعد الظهر.", "n3")]),
            _n("n2b", "That can definitely cause headaches too. When did it start?",
               "هذا قد يسبب الصداع أيضاً بالتأكيد. متى بدأ؟",
               [("About a week ago, work has been stressful.", "منذ حوالي أسبوع، كان العمل مرهقاً.", "n3")]),
            _n("n3", "Okay. Have you been drinking enough water and sleeping well?",
               "حسناً. هل تشرب كمية كافية من الماء وتنام جيداً؟",
               [("Honestly, not really — I've been very busy.", "بصراحة، ليس تماماً — كنت مشغولاً جداً.", "n4a"),
                ("I've been trying, but it's been hard to relax.", "كنت أحاول، لكن كان من الصعب الاسترخاء.", "n4b")]),
            _n("n4a", "That's likely a big part of it. Let's start there.",
               "هذا على الأرجح جزء كبير من السبب. لنبدأ من هناك.",
               [("Makes sense, I'll work on that.", "منطقي، سأعمل على ذلك.", "n5")]),
            _n("n4b", "Stress headaches are very common — you're not alone in this.",
               "صداع التوتر شائع جداً — لست وحدك في هذا.",
               [("Good to know, it's been worrying me.", "جيد أن أعرف، كان يقلقني ذلك.", "n5")]),
            _n("n5", "Any other symptoms — nausea, sensitivity to light?",
               "أي أعراض أخرى — غثيان، حساسية للضوء؟",
               [("No, nothing like that, just the headache.", "لا، لا شيء من ذلك، فقط الصداع.", "n6")]),
            _n("n6", "Good, that rules out a few things. I'll suggest some simple steps.",
               "جيد، هذا يستبعد بعض الأمور. سأقترح بعض الخطوات البسيطة.",
               [("Please, I'm ready to hear them.", "من فضلك، أنا مستعد لسماعها.", "n7")]),
            _n("n7", "Rest, drink water, and try to sleep at a regular time each night.",
               "ارتح، اشرب الماء، وحاول أن تنام في وقت منتظم كل ليلة.",
               [("I'll do my best to follow that.", "سأبذل قصارى جهدي لاتباع ذلك.", "n8")]),
            _n("n8", "If it doesn't improve in a week, come back and we'll look further.",
               "إن لم يتحسن خلال أسبوع، عُد وسننظر بشكل أعمق.",
               [("Thank you, doctor. I appreciate your help.", "شكراً لك دكتور. أقدّر مساعدتك.", "end")]),
            _n("end", "🩺 (Clear communication with your doctor. Well done!)",
               "🩺 (تواصل واضح مع طبيبك. أحسنت!)", end=True),
        ],
    },
    {
        "id": "landlord",
        "title": "Talking to your landlord",
        "level": "Intermediate",
        "emoji": "🔑",
        "setting": "The heating in your apartment has been broken for two days.",
        "goal": "Explain the problem clearly and agree on a fix date.",
        "is_premium": True,
        "start": "n1",
        "nodes": [
            _n("n1", "Hello? Is everything okay with the apartment?",
               "مرحباً؟ هل كل شيء بخير في الشقة؟",
               [("Actually, the heating hasn't worked for two days.", "في الواقع، التدفئة لا تعمل منذ يومين.", "n2a"),
                ("There's a small issue I wanted to mention.", "هناك مشكلة بسيطة أردت ذكرها.", "n2b")]),
            _n("n2a", "Oh no, I'm sorry to hear that. Have you tried resetting it?",
               "أوه، يؤسفني سماع ذلك. هل حاولت إعادة تشغيلها؟",
               [("Yes, I tried, but it still doesn't work.", "نعم، حاولت، لكنها ما زالت لا تعمل.", "n3")]),
            _n("n2b", "Go ahead, what's going on?",
               "تفضل، ما الأمر؟",
               [("The heating stopped working two days ago.", "توقفت التدفئة عن العمل منذ يومين.", "n3")]),
            _n("n3", "Understood. Has it been very cold in there?",
               "مفهوم. هل كان الجو بارداً جداً في الداخل؟",
               [("Yes, quite uncomfortable at night especially.", "نعم، غير مريح جداً خاصة ليلاً.", "n4a"),
                ("It's manageable, but I'd like it fixed soon.", "يمكن تحمله، لكنني أود إصلاحه قريباً.", "n4b")]),
            _n("n4a", "That's not okay, I'll prioritize this right away.",
               "هذا غير مقبول، سأعطي الأولوية لهذا فوراً.",
               [("I appreciate that, thank you.", "أقدّر ذلك، شكراً لك.", "n5")]),
            _n("n4b", "Understood, I'll get someone out as soon as I can.",
               "مفهوم، سأرسل أحداً بأسرع ما يمكن.",
               [("That sounds good to me.", "هذا مناسب بالنسبة لي.", "n5")]),
            _n("n5", "I'll send someone tomorrow morning to take a look.",
               "سأرسل أحداً غداً صباحاً لإلقاء نظرة.",
               [("That works. What time should I expect them?", "هذا مناسب. متى يجب أن أتوقع وصولهم؟", "n6")]),
            _n("n6", "Around nine, if that's convenient for you.",
               "حوالي الساعة التاسعة، إن كان ذلك مناسباً لك.",
               [("That's perfect, I'll be home then.", "هذا ممتاز، سأكون في المنزل حينها.", "n7")]),
            _n("n7", "Great. I'll also give you a call once it's fixed.",
               "رائع. سأتصل بك أيضاً بمجرد إصلاحها.",
               [("Thank you for sorting it out so quickly.", "شكراً لحل الأمر بهذه السرعة.", "n8")]),
            _n("n8", "Of course — sorry again for the trouble.",
               "بالطبع — آسف مرة أخرى على الإزعاج.",
               [("No worries, I appreciate you taking care of it.", "لا مشكلة، أقدّر اهتمامك بالأمر.", "end")]),
            _n("end", "🔑 (Firm but polite — problem solved.)",
               "🔑 (حازم لكن مؤدب — تم حل المشكلة.)", end=True),
        ],
    },
    {
        "id": "presentation",
        "title": "Giving a work presentation",
        "level": "Advanced",
        "emoji": "📊",
        "setting": "You're presenting quarterly results and a colleague pushes back.",
        "goal": "Defend your numbers calmly and propose a next step.",
        "is_premium": True,
        "start": "n1",
        "nodes": [
            _n("n1", "Thanks for the presentation. I have to say, I'm surprised by these numbers.",
               "شكراً على العرض. يجب أن أقول إنني متفاجئ بهذه الأرقام.",
               [("I understand — could you tell me which part concerns you?", "أفهم — هل يمكنك إخباري بأي جزء يقلقك؟", "n2a"),
                ("Sure, happy to walk through the reasoning.", "بالتأكيد، يسعدني شرح المنطق وراءها.", "n2b")]),
            _n("n2a", "The growth in Q3 seems too optimistic compared to Q2.",
               "يبدو نمو الربع الثالث متفائلاً جداً مقارنة بالربع الثاني.",
               [("That's fair. It's based on the new product launch data.", "هذا منطقي. إنه مبني على بيانات إطلاق المنتج الجديد.", "n3")]),
            _n("n2b", "Well, mainly the growth in Q3 — where's that number coming from?",
               "حسناً، بشكل أساسي نمو الربع الثالث — من أين يأتي هذا الرقم؟",
               [("It's based on the new product launch data.", "إنه مبني على بيانات إطلاق المنتج الجديد.", "n3")]),
            _n("n3", "Ah, I wasn't aware of that. How reliable is that data source?",
               "آه، لم أكن أعلم بذلك. ما مدى موثوقية مصدر البيانات هذا؟",
               [("Very reliable — it's the same system we've used for two years.", "موثوق جداً — نفس النظام الذي نستخدمه منذ عامين.", "n4a"),
                ("It's new, but the early signals are consistent.", "جديد، لكن المؤشرات المبكرة متسقة.", "n4b")]),
            _n("n4a", "That gives me more confidence. Thanks for clarifying.",
               "هذا يمنحني ثقة أكبر. شكراً على التوضيح.",
               [("Of course, happy to answer anything else too.", "بالطبع، يسعدني الإجابة عن أي شيء آخر أيضاً.", "n5")]),
            _n("n4b", "I see — so there's still some uncertainty then.",
               "أفهم — إذاً لا يزال هناك بعض عدم اليقين.",
               [("A little, yes, but the trend is promising so far.", "قليلاً، نعم، لكن الاتجاه واعد حتى الآن.", "n5")]),
            _n("n5", "Fair enough. What would you recommend as a next step?",
               "معقول. ماذا تنصح كخطوة قادمة؟",
               [("I'd suggest we revisit the forecast after next month's data.", "أقترح أن نراجع التوقعات بعد بيانات الشهر القادم.", "n6")]),
            _n("n6", "That sounds reasonable. Should we flag this to the wider team?",
               "يبدو هذا معقولاً. هل يجب أن نبلغ الفريق الأوسع بهذا؟",
               [("Good idea, I'll send a short summary after this meeting.", "فكرة جيدة، سأرسل ملخصاً موجزاً بعد هذا الاجتماع.", "n7")]),
            _n("n7", "That would help a lot. Thanks for clarifying everything.",
               "سيساعد ذلك كثيراً. شكراً على توضيح كل شيء.",
               [("Of course — happy to walk through it in more detail anytime.", "بالطبع — يسعدني شرحها بمزيد من التفصيل في أي وقت.", "n8")]),
            _n("n8", "Appreciate that. I feel a lot more confident in the numbers now.",
               "أقدّر ذلك. أشعر بثقة أكبر بكثير في الأرقام الآن.",
               [("Great, that's exactly what I was hoping for.", "رائع، هذا بالضبط ما كنت آمله.", "end")]),
            _n("end", "📊 (Calm, evidence-based, professional. Great job.)",
               "📊 (هادئ، مبني على أدلة، ومهني. عمل رائع.)", end=True),
        ],
    },
    {
        "id": "negotiation",
        "title": "Negotiating a salary",
        "level": "Advanced",
        "emoji": "💰",
        "setting": "You've been offered a job, but the salary is below what you hoped.",
        "goal": "Make your case for a higher offer, respectfully but firmly.",
        "is_premium": True,
        "start": "n1",
        "nodes": [
            _n("n1", "We'd love to offer you the position at $55,000 a year.",
               "يسعدنا أن نعرض عليك المنصب براتب 55,000 دولار سنوياً.",
               [("Thank you — I was hoping for something closer to $62,000.", "شكراً لك — كنت آمل بشيء أقرب إلى 62,000 دولار.", "n2a"),
                ("I'm excited about the role, but the number is lower than I expected.", "أنا متحمس للدور، لكن الرقم أقل مما توقعت.", "n2b")]),
            _n("n2a", "That's a bit more than we budgeted. Can you tell me why?",
               "هذا أكثر قليلاً مما خصصناه في الميزانية. هل يمكنك إخباري لماذا؟",
               [("Based on my experience and market research, that's the going rate.", "بناءً على خبرتي وأبحاث السوق، هذا هو المعدل السائد.", "n3")]),
            _n("n2b", "I understand. What figure did you have in mind?",
               "أفهم. ما الرقم الذي كان في ذهنك؟",
               [("Around $62,000, based on similar roles in the market.", "حوالي 62,000 دولار، بناءً على أدوار مماثلة في السوق.", "n3")]),
            _n("n3", "That's reasonable. Let me see what flexibility we have.",
               "هذا معقول. دعني أرى ما المرونة المتاحة لدينا.",
               [("I appreciate that. I'm confident we can find a number that works.", "أقدّر ذلك. أنا واثق أننا سنجد رقماً مناسباً للطرفين.", "n4")]),
            _n("n4", "We could go up to $58,000. Would that work for you?",
               "يمكننا الوصول إلى 58,000 دولار. هل يناسبك ذلك؟",
               [("That's closer, but could we also discuss a review after six months?", "هذا أقرب، لكن هل يمكننا مناقشة مراجعة بعد ستة أشهر؟", "n5a"),
                ("I appreciate the movement — could we meet in the middle at $60,000?", "أقدّر هذا التقدم — هل يمكننا الاتفاق في المنتصف عند 60,000؟", "n5b")]),
            _n("n5a", "A review after six months is fair — we can agree to that.",
               "المراجعة بعد ستة أشهر عادلة — يمكننا الاتفاق على ذلك.",
               [("That works well for me, thank you.", "هذا مناسب لي، شكراً لك.", "n6")]),
            _n("n5b", "Let me check with the team, but that seems doable.",
               "دعني أتحقق مع الفريق، لكن يبدو ذلك ممكناً.",
               [("I appreciate you considering it.", "أقدّر أخذك ذلك بعين الاعتبار.", "n6")]),
            _n("n6", "Alright, let's finalize the details and send you the offer today.",
               "حسناً، لننهي التفاصيل ونرسل لك العرض اليوم.",
               [("That sounds great, thank you for working with me on this.", "يبدو ذلك رائعاً، شكراً للتعاون معي في هذا.", "n7")]),
            _n("n7", "Of course — we're glad to have you join the team.",
               "بالطبع — يسعدنا انضمامك للفريق.",
               [("I'm looking forward to getting started.", "أتطلع للبدء.", "end")]),
            _n("end", "💰 (Confident, respectful negotiation. Well earned!)",
               "💰 (تفاوض واثق ومحترم. استحققته!)", end=True),
        ],
    },
]
CONVERSATION_BY_ID = {c["id"]: c for c in CONVERSATIONS}


# ----------------------------------------------------------------------
# 3) SPRINT DAY CONVERSATIONS — one short scripted dialogue per day
# ----------------------------------------------------------------------
# Each is a compact 3-4 turn branching chat matching that day's theme.
# Shorter than the standalone scenarios above, since it's stage 2 after
# the drill. Same node shape.
SPRINT_CONVS = {
    1: {"setting": "A conference coffee break. A friendly stranger says hello.",
        "goal": "Introduce yourself and ask them something back.",
        "start": "a",
        "nodes": [
            _n("a", "Hi there — I don't think we've met. I'm Sam.",
               "مرحباً — لا أظن أننا التقينا. أنا سام.",
               [("Hi Sam, I'm Ali. Nice to meet you.", "مرحباً سام، أنا علي. سعيد بلقائك.", "b")]),
            _n("b", "Nice to meet you too, Ali. Are you enjoying the event?",
               "سعيد بلقائك أيضاً يا علي. هل تستمتع بالفعالية؟",
               [("Yes, it's great. What about you?", "نعم، إنها رائعة. وأنت؟", "c")]),
            _n("c", "Loving it. It's been great chatting with you!",
               "أحبها. كان من الرائع الدردشة معك!",
               [("You too — see you around!", "وأنت كذلك — أراك لاحقاً!", "end")]),
            _n("end", "✓ Nicely done.", "✓ أحسنت.", end=True),
        ]},
    2: {"setting": "A new neighbor knocks to say hello.",
        "goal": "Tell them where you're from and what you do.",
        "start": "a",
        "nodes": [
            _n("a", "Hi! I'm your new neighbor, Maya. Where are you from?",
               "مرحباً! أنا جارتك الجديدة مايا. من أين أنت؟",
               [("Hi Maya. I'm originally from Najaf.", "مرحباً مايا. أنا في الأصل من النجف.", "b")]),
            _n("b", "Oh lovely! And what do you do?",
               "أوه جميل! وماذا تعمل؟",
               [("I work as a researcher.", "أعمل كباحث.", "c")]),
            _n("c", "That's wonderful. Welcome to the building!",
               "هذا رائع. أهلاً بك في المبنى!",
               [("Thank you, that's very kind.", "شكراً، هذا لطف كبير منك.", "end")]),
            _n("end", "✓ Warm and clear.", "✓ ودّي وواضح.", end=True),
        ]},
    3: {"setting": "Monday morning by the coffee machine at work.",
        "goal": "Make small talk about the weekend and end politely.",
        "start": "a",
        "nodes": [
            _n("a", "Morning! Did you have a good weekend?",
               "صباح الخير! هل قضيت عطلة نهاية أسبوع جيدة؟",
               [("Yes, really relaxing. How about you?", "نعم، كانت مريحة جداً. وأنت؟", "b")]),
            _n("b", "Pretty busy, but good. Anyway, I'd better get to work.",
               "مشغولة نوعاً ما، لكن جيدة. على أي حال، من الأفضل أن أبدأ العمل.",
               [("Of course — have a good one!", "بالطبع — أتمنى لك يوماً طيباً!", "end")]),
            _n("end", "✓ Easy and natural.", "✓ سهل وطبيعي.", end=True),
        ]},
    4: {"setting": "A library. You can't find the printer.",
        "goal": "Ask for help and confirm you understood.",
        "start": "a",
        "nodes": [
            _n("a", "Hi, you look like you need something?",
               "مرحباً، يبدو أنك تحتاج شيئاً؟",
               [("Yes, excuse me — where's the printer?", "نعم، المعذرة — أين الطابعة؟", "b")]),
            _n("b", "It's just around the corner, next to the window.",
               "إنها خلف الزاوية مباشرة، بجانب النافذة.",
               [("Around the corner by the window — got it, thanks!", "خلف الزاوية بجانب النافذة — فهمت، شكراً!", "end")]),
            _n("end", "✓ Clear and polite.", "✓ واضح ومؤدب.", end=True),
        ]},
    5: {"setting": "A restaurant. The waiter comes to take your order.",
        "goal": "Order a meal and ask for the bill.",
        "start": "a",
        "nodes": [
            _n("a", "Good evening! Are you ready to order?",
               "مساء الخير! هل أنت مستعد للطلب؟",
               [("Yes, I'd like the grilled chicken, please.", "نعم، أريد الدجاج المشوي من فضلك.", "b")]),
            _n("b", "Excellent choice. Anything to drink?",
               "اختيار ممتاز. أي شيء للشرب؟",
               [("Just water, thanks. And could we have the bill after?", "ماء فقط، شكراً. وهل يمكننا الحصول على الفاتورة بعد ذلك؟", "c")]),
            _n("c", "Of course, I'll bring it shortly. Enjoy your meal!",
               "بالطبع، سأحضرها قريباً. استمتع بوجبتك!",
               [("Thank you very much.", "شكراً جزيلاً.", "end")]),
            _n("end", "✓ Smoothly ordered.", "✓ طلب سلس.", end=True),
        ]},
    6: {"setting": "A market stall. You like a jacket but the price is high.",
        "goal": "Ask the price and try to negotiate.",
        "start": "a",
        "nodes": [
            _n("a", "That jacket suits you! It's fifty dollars.",
               "تلك السترة تناسبك! سعرها خمسون دولاراً.",
               [("That's a bit much. Could you do forty?", "هذا كثير قليلاً. هل يمكنك جعله أربعين؟", "b")]),
            _n("b", "Hmm... I can do forty-five. That's my best price.",
               "همم... يمكنني خمسة وأربعين. هذا أفضل سعر لدي.",
               [("Alright, forty-five works. I'll take it.", "حسناً، خمسة وأربعون مناسب. سآخذها.", "end")]),
            _n("end", "✓ Good negotiating!", "✓ مساومة جيدة!", end=True),
        ]},
    7: {"setting": "A phone call with an old friend you haven't spoken to in months.",
        "goal": "Tell them one thing that happened to you recently.",
        "start": "a",
        "nodes": [
            _n("a", "Hey! It's been ages. What have you been up to?",
               "مرحباً! لقد مضى وقت طويل. ماذا كنت تفعل؟",
               [("Actually, guess what — I started a new job!", "في الواقع، خمّن ماذا — بدأت وظيفة جديدة!", "b")]),
            _n("b", "No way! How's it going so far?",
               "مستحيل! كيف تسير الأمور حتى الآن؟",
               [("Really well, I'm enjoying it a lot.", "بشكل جيد جداً، أستمتع بها كثيراً.", "c")]),
            _n("c", "That's fantastic news. I'm so happy for you!",
               "هذه أخبار رائعة. أنا سعيد جداً من أجلك!",
               [("Thanks! We should catch up properly soon.", "شكراً! يجب أن نلتقي قريباً كما ينبغي.", "end")]),
            _n("end", "✓ Great storytelling.", "✓ سرد رائع.", end=True),
        ]},
    8: {"setting": "A colleague chats with you before a meeting about a decision.",
        "goal": "Give your opinion and respond to theirs.",
        "start": "a",
        "nodes": [
            _n("a", "So, what do you think — should we go with option A?",
               "إذاً، ما رأيك — هل نختار الخيار أ؟",
               [("In my opinion, option B is safer.", "في رأيي، الخيار ب أكثر أماناً.", "b")]),
            _n("b", "Hmm, why do you say that?",
               "همم، لماذا تقول ذلك؟",
               [("It costs less and carries less risk.", "يكلف أقل ويحمل مخاطر أقل.", "c")]),
            _n("c", "That's a fair point. Let's suggest it together.",
               "هذه نقطة وجيهة. لنقترحها معاً.",
               [("Sounds good to me.", "يبدو جيداً بالنسبة لي.", "end")]),
            _n("end", "✓ Well argued.", "✓ حجة جيدة.", end=True),
        ]},
    9: {"setting": "A classmate has a strong idea for your group project.",
        "goal": "Disagree politely and offer an alternative.",
        "start": "a",
        "nodes": [
            _n("a", "I think we should do the whole thing as a video.",
               "أعتقد أننا يجب أن نصنع كل شيء كفيديو.",
               [("I see your point, but that might take too long.", "أفهم وجهة نظرك، لكن ذلك قد يستغرق وقتاً طويلاً.", "b")]),
            _n("b", "Oh... so what would you suggest instead?",
               "أوه... فماذا تقترح بدلاً من ذلك؟",
               [("What if we did slides with a short clip?", "ماذا لو صنعنا شرائح مع مقطع قصير؟", "c")]),
            _n("c", "Actually, that's a good compromise. Let's do that.",
               "في الواقع، هذا حل وسط جيد. لنفعل ذلك.",
               [("Great, glad we agree.", "رائع، سعيد أننا اتفقنا.", "end")]),
            _n("end", "✓ Disagreed without friction.", "✓ اختلفت دون توتر.", end=True),
        ]},
    10: {"setting": "A phone call to a dentist's office to change an appointment.",
         "goal": "Explain why you're calling and agree on a new time.",
         "start": "a",
         "nodes": [
            _n("a", "Good morning, Bright Smile Dental. How can I help?",
               "صباح الخير، عيادة برايت سمايل. كيف يمكنني المساعدة؟",
               [("Hi, I'd like to change my appointment on Monday.", "مرحباً، أود تغيير موعدي يوم الاثنين.", "b")]),
            _n("b", "No problem. How about Wednesday at 3 pm?",
               "لا مشكلة. ما رأيك بالأربعاء الساعة الثالثة مساءً؟",
               [("Wednesday at 3 works perfectly.", "الأربعاء الساعة الثالثة مناسب تماماً.", "c")]),
            _n("c", "Great, you're all booked. See you then!",
               "رائع، تم الحجز. أراك حينها!",
               [("Thank you, goodbye.", "شكراً، مع السلامة.", "end")]),
            _n("end", "✓ Sorted clearly.", "✓ تم بوضوح.", end=True),
        ]},
    11: {"setting": "Your manager checks in on your project.",
         "goal": "Explain your work and agree on a next step.",
         "start": "a",
         "nodes": [
            _n("a", "Hi, how's the project coming along?",
               "مرحباً، كيف يسير المشروع؟",
               [("It's going well. I've finished the first part.", "يسير بشكل جيد. أنهيت الجزء الأول.", "b")]),
            _n("b", "Great. When can you have the rest ready?",
               "رائع. متى يمكنك تجهيز الباقي؟",
               [("I can have it done by Friday.", "يمكنني إنهاؤه بحلول يوم الجمعة.", "c")]),
            _n("c", "Perfect. Let's review it together then.",
               "ممتاز. لنراجعه معاً حينها.",
               [("Sounds good, I'll send it over.", "يبدو جيداً، سأرسله.", "end")]),
            _n("end", "✓ Professional and clear.", "✓ مهني وواضح.", end=True),
        ]},
    12: {"setting": "A hotel receptionist as you check in and want to explore.",
         "goal": "Ask how to reach the city center and how long it takes.",
         "start": "a",
         "nodes": [
            _n("a", "Welcome! Here's your room key. Anything else?",
               "أهلاً بك! تفضل مفتاح غرفتك. أي شيء آخر؟",
               [("Yes, how do I get to the city center?", "نعم، كيف أصل إلى وسط المدينة؟", "b")]),
            _n("b", "Take the number 5 bus right outside.",
               "خذ الحافلة رقم 5 الموجودة بالخارج مباشرة.",
               [("Great. How long does it take?", "رائع. كم يستغرق ذلك؟", "c")]),
            _n("c", "About fifteen minutes. Enjoy your stay!",
               "حوالي خمس عشرة دقيقة. استمتع بإقامتك!",
               [("Thank you, that's very helpful.", "شكراً، هذا مفيد جداً.", "end")]),
            _n("end", "✓ All the info you needed.", "✓ كل المعلومات التي تحتاجها.", end=True),
        ]},
    13: {"setting": "A shop. Something you bought stopped working.",
         "goal": "Explain the problem and say what you want done.",
         "start": "a",
         "nodes": [
            _n("a", "Hi, what can I do for you?",
               "مرحباً، ماذا يمكنني أن أفعل لك؟",
               [("There's a problem with this — it stopped working.", "هناك مشكلة في هذا — توقف عن العمل.", "b")]),
            _n("b", "I'm sorry about that. What would you like to do?",
               "أعتذر عن ذلك. ماذا تود أن تفعل؟",
               [("I'd like a replacement, please.", "أود استبدالاً من فضلك.", "c")]),
            _n("c", "Absolutely. Let me get you a new one.",
               "بالتأكيد. دعني أحضر لك واحداً جديداً.",
               [("Thank you, I appreciate it.", "شكراً، أقدّر ذلك.", "end")]),
            _n("end", "✓ Handled firmly and politely.", "✓ تم التعامل بحزم وأدب.", end=True),
        ]},
    14: {"setting": "A friend asks how your two weeks of practice went.",
         "goal": "Describe how it went and say what's next.",
         "start": "a",
         "nodes": [
            _n("a", "So, you finished the two weeks! How was it?",
               "إذاً، أنهيت الأسبوعين! كيف كان الأمر؟",
               [("Honestly, at first it was hard, but I improved a lot.", "بصراحة، في البداية كان صعباً، لكنني تحسنت كثيراً.", "b")]),
            _n("b", "That's amazing. What will you do now?",
               "هذا مذهل. ماذا ستفعل الآن؟",
               [("Going forward, I'll keep practicing every day.", "من الآن فصاعداً، سأواصل التدرب كل يوم.", "c")]),
            _n("c", "I'm really proud of you. Keep it up!",
               "أنا فخور بك حقاً. استمر!",
               [("Thanks for asking — it means a lot.", "شكراً لسؤالك — هذا يعني لي الكثير.", "end")]),
            _n("end", "🎉 You did it. Fourteen days of real speaking!",
               "🎉 لقد فعلتها. أربعة عشر يوماً من التحدث الحقيقي!", end=True),
        ]},
}


# ----------------------------------------------------------------------
# 4) SHADOW MODE — connected-speech / rhythm training, no AI required
# ----------------------------------------------------------------------
# Correct grammar and vocabulary aren't what make learners sound non-native —
# it's usually PROSODY: the rhythm, linking, and reductions native speakers
# use automatically. "Shadowing" (speaking along WITH a recording, not after
# it) is the classic technique interpreters and accent coaches use to train
# exactly this, and it needs no AI: just a native-ish audio model (the
# browser's own text-to-speech) and a mirror (the learner's own recording,
# played back immediately for a direct before/after comparison).
#
# Each phrase carries a short "tip" explaining the real phonetic feature at
# play (linking, flapping, reduction, stress-timing) — these are standard,
# well-documented features of spoken English, not guesses.
SHADOW_CATEGORIES = [
    {
        "id": "contractions",
        "title": "Contractions in the Wild",
        "level": "Beginner",
        "is_premium": False,
        "focus": "Casual reductions native speakers use even in everyday careful speech.",
        "phrases": [
            {"en": "What are you going to do this weekend?",
             "ar": "ماذا ستفعل في نهاية هذا الأسبوع؟",
             "tip": "\"going to\" naturally blends into \"gonna\" — try saying it fast, not word by word."},
            {"en": "I want to try that new restaurant.",
             "ar": "أريد تجربة ذلك المطعم الجديد.",
             "tip": "\"want to\" blends into \"wanna\" in relaxed natural speech."},
            {"en": "I have got to finish this today.",
             "ar": "يجب أن أنهي هذا اليوم.",
             "tip": "\"got to\" collapses into \"gotta\" — don't pronounce every letter."},
            {"en": "Give me a minute, please.",
             "ar": "أعطني دقيقة من فضلك.",
             "tip": "\"give me\" often blends into \"gimme\" when spoken casually."},
            {"en": "I kind of like it, actually.",
             "ar": "يعجبني إلى حد ما في الواقع.",
             "tip": "\"kind of\" reduces to \"kinda\" — the \"of\" almost disappears."},
        ],
    },
    {
        "id": "linking",
        "title": "Linking Sounds Together",
        "level": "Beginner",
        "is_premium": False,
        "focus": "English doesn't pause between words — the last sound and next word blend.",
        "phrases": [
            {"en": "Turn it off before you leave.",
             "ar": "أطفئه قبل أن تغادر.",
             "tip": "\"turn it\" links into one flowing sound — no gap between the words."},
            {"en": "I need an umbrella today.",
             "ar": "أحتاج مظلة اليوم.",
             "tip": "\"need an\" links smoothly — the consonant slides straight into the vowel."},
            {"en": "Check it out when you have time.",
             "ar": "تحقق منه عندما يكون لديك وقت.",
             "tip": "\"check it\" links together like one word."},
            {"en": "Pick up your bag before we go.",
             "ar": "احمل حقيبتك قبل أن نذهب.",
             "tip": "\"pick up\" links — the two words flow into each other."},
            {"en": "Wait a minute, please.",
             "ar": "انتظر دقيقة من فضلك.",
             "tip": "\"wait a\" links smoothly, almost like \"way-ta\"."},
        ],
    },
    {
        "id": "flap-t",
        "title": "The American Flap T",
        "level": "Intermediate",
        "is_premium": True,
        "focus": "In American English, a T between vowels softens into a quick \"d\" tap.",
        "phrases": [
            {"en": "Can you get me a bottle of water?",
             "ar": "هل يمكنك إحضار زجاجة ماء لي؟",
             "tip": "\"water\" and \"bottle\" both use the soft flap — the T sounds almost like a fast \"d\"."},
            {"en": "That's a lot better than before.",
             "ar": "هذا أفضل بكثير من ذي قبل.",
             "tip": "\"better\" flaps its middle T into a quick, light \"d\" sound."},
            {"en": "I'll meet you at the party later.",
             "ar": "سأقابلك في الحفلة لاحقاً.",
             "tip": "\"party\" and \"later\" both flap their T the same way."},
            {"en": "What time is it right now?",
             "ar": "كم الساعة الآن؟",
             "tip": "before a consonant, \"what\"'s T often almost disappears entirely."},
            {"en": "Let it go, it's not a big deal.",
             "ar": "دعه يذهب، إنه ليس أمراً مهماً.",
             "tip": "\"let it\" links and flaps together into one smooth sound."},
        ],
    },
    {
        "id": "stress-rhythm",
        "title": "Sentence Stress & Rhythm",
        "level": "Advanced",
        "is_premium": True,
        "focus": "English is stress-timed: key words are stretched and loud, small words rush by quiet and fast.",
        "phrases": [
            {"en": "I didn't say she stole the money.",
             "ar": "لم أقل إنها سرقت المال.",
             "tip": "stress falls on the meaning-carrying words — try leaning hard on \"didn't\", then \"stole\"."},
            {"en": "I can't believe you did that.",
             "ar": "لا أستطيع أن أصدق أنك فعلت ذلك.",
             "tip": "stretch \"can't\" and \"believe\", then rush lightly through \"you did\"."},
            {"en": "It's not what you think it is.",
             "ar": "الأمر ليس كما تعتقد.",
             "tip": "keep \"not\" and \"think\" strong and clear, let the small words fall away quietly."},
            {"en": "She's the one who told me first.",
             "ar": "هي من أخبرتني أولاً.",
             "tip": "emphasize \"she's\" and \"first\" — glide quickly through the words in between."},
            {"en": "That's exactly what I meant.",
             "ar": "هذا بالضبط ما قصدته.",
             "tip": "\"exactly\" carries the whole sentence — give it real weight and length."},
        ],
    },
]
